version: '3.1'

services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  nginx:
    build: ./nginx
    depends_on:
      - web
    volumes:
      - ./logs/nginx:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
  db:
    image: postgres:10-alpine
    volumes:
      - postgres:/var/lib/postgres/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: obscura-dev
    ports:
      - 5432:5432
  adminer:
    image: adminer:4
    ports:
      - 8080:8080
    depends_on:
      - db
        
volumes:
  postgres:
    driver: local