version: '3.1'

services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
  nginx:
    build: ./nginx
    depends_on:
      - web
    volumes:
      - ./logs/nginx:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
  